# Generated by Django 4.2 on 2023-04-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='votes',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
